/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable, from, switchMap } from "rxjs";
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Application } from '../../models/application';

export interface GetApplications$Params {}

export function getApplications(http: HttpClient, rootUrl: string, params?: GetApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Application>>> {
  const rb = new RequestBuilder(rootUrl, getApplications.PATH, 'get');
  if (params) {
    // You can add any params processing here if required
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<Blob> => r instanceof HttpResponse), // Ensure it's a valid HttpResponse
    map((r: HttpResponse<Blob>) => r.body), // Extract the blob body
    map((blob: Blob) => {
      // Convert the Blob to JSON and return it as an Observable
      return from(convertBlobToJson(blob)); // Convert Promise to Observable
    }),
    // Flatten the Observable so we can access the actual data
    switchMap((applicationsObservable: Observable<Application[]>) => applicationsObservable),
    map((applications: Application[]) => {
      // Return the response in the expected format
      return {
        body: applications
      } as StrictHttpResponse<Array<Application>>;
    })
  );
}

getApplications.PATH = '/application/getall';

// Function to convert Blob to JSON
function convertBlobToJson(blob: Blob): Promise<Application[]> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      try {
        // Parse the Blob's text content into JSON
        const json = JSON.parse(reader.result as string);
        resolve(json);
      } catch (error) {
        reject('Error parsing Blob to JSON');
      }
    };
    reader.readAsText(blob);
  });
}
