/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addCv1 } from '../fn/cv-controller/add-cv-1';
import { AddCv1$Params } from '../fn/cv-controller/add-cv-1';

@Injectable({ providedIn: 'root' })
export class CvControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addCv1()` */
  static readonly AddCv1Path = '/cv/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addCv1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCv1$Response(params: AddCv1$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addCv1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addCv1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCv1(params: AddCv1$Params, context?: HttpContext): Observable<number> {
    return this.addCv1$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
