/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addoffre } from '../fn/offre-controller/addoffre';
import { Addoffre$Params } from '../fn/offre-controller/addoffre';

@Injectable({ providedIn: 'root' })
export class OffreControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addoffre()` */
  static readonly AddoffrePath = '/offre/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addoffre()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addoffre$Response(params: Addoffre$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addoffre(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addoffre$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addoffre(params: Addoffre$Params, context?: HttpContext): Observable<number> {
    return this.addoffre$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
