/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addOffre } from '../fn/offre-controller/add-offre';
import { AddOffre$Params } from '../fn/offre-controller/add-offre';

@Injectable({ providedIn: 'root' })
export class OffreControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addOffre()` */
  static readonly AddOffrePath = '/offre/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addOffre()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addOffre$Response(params: AddOffre$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addOffre(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addOffre$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addOffre(params: AddOffre$Params, context?: HttpContext): Observable<number> {
    return this.addOffre$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
