/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cv } from '../models/cv';
import { Feedback } from '../models/feedback';
export interface Application {
  createdBy?: number;
  cv?: Cv;
  feedback?: Feedback;
  id?: number;
  motivatedlettre?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  studentId?: number;
}
