/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cv } from '../models/cv';
import { Feedback } from '../models/feedback';
import { Offre } from '../models/offre';
export interface Application {
  createdBy?: number;
  cv?: Cv;
  cvid?: number;
  feedback?: Feedback;
  id?: number;
  motivatedlettre?: string;
  offre?: Offre;
  offreId?: number;
  pdfDownloadLink?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  studentId?: number;
  username?: string;
  score?: Number;

}
