/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cv {
  contactinfo?: string;
  createdBy?: string;
  education?: string;
  experience?: string;
  getstudentname?: string;
  id?: number;
  name?: string;
  pdfDownloadLink?: string;
  skills?: string;
}
