/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Cv {
  contactinfo?: string;
  createdBy?: string;
  education?: string;
  experience?: string;
  id?: number;
  name?: string;
  pdfDownloadLink?: string;
  skills?: string;
  student?: User;
}
