/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Application } from '../models/application';
import { User } from '../models/user';
export interface Offre {
  applications?: Array<Application>;
  createdBy?: number;
  description?: string;
  id?: number;
  rh?: User;
  skills?: string;
  title?: string;
}
