/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Offre {
  createdBy?: number;
  description?: string;
  id?: number;
  imageUrl?: string;
  skills?: string;
  title?: string;
}
