/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  authority?: string;
  id?: number;
  name?: 'ROLE_ADMIN' | 'ROLE_CLIENT' | 'ROLE_PROVIDER' | 'ROLE_HR';
}
